ipmitool/ipmitool

lib/ipmi_fru.c

Executing "ipmitool fru internaluse 1 info" command and run into the line #4098 which is within ipmi_fru_get_internal_use_info() function will result to segmentation fault.

Fix the fatal error which result from execting 'ipmitool fru internaluse 1 info'

---

include/ipmitool/ipmi_user.h
lib/ipmi_user.c

In multiple places throughout ipmi_user.c a user id mask
was used as a magic number, in some places the mask was wrong.
This commit replaces all those magic numbers with a single
IPMI_UID() macro.
Resolves ipmitool/ipmitool#6

GH-6: Replace user_id masks with a macro

---

src/plugins/open/open.c

The select syscall can be interrupted for signals like SIGPROF. The IPMI
command sent will still be outstanding but the send_command will return
an error. When the next command is sent it will get the completion for
the previous command and has the tendency to break state of end users.

plugins/open: Fix for interrupted select

---

include/ipmitool/Makefile.am
include/ipmitool/ipmi_quantaoem.h
lib/Makefile.am
lib/ipmi_main.c
lib/ipmi_oem.c
lib/ipmi_quantaoem.c
lib/ipmi_sel.c
src/ipmitool.c

Hi, Mr. Amelkin:
I posted ticket with https://sourceforge.net/p/ipmitool/bugs/511/ on SourceForge.
I have forked ipmitool and try "Pull Request" to request merge to "ipmitool" code.
Thank you

Add Quanta OEM code: ipmitool for DIMM slot readable feature

---

src/plugins/open/open.c

The ioctl to enable the event receiver in the OpenIPMI interface is
called with an argument of 0, which tells OpenIPMI to disable it. Set
the argument to 1 instead so that it will be enabled.
Signed-off-by: Benjamin Fair <benjaminfair@google.com>

plugins: open: Properly enable event receiver

---

src/plugins/lanplus/lanplus_crypt_impl.c

From the man page:
EVP_CIPHER_CTX was made opaque in OpenSSL 1.1.0. As a result,
EVP_CIPHER_CTX_reset() appeared and EVP_CIPHER_CTX_cleanup() disappeared.
EVP_CIPHER_CTX_init() remains as an alias for EVP_CIPHER_CTX_reset().
Signed-off-by: Rosen Penev <rosenp@gmail.com>

lanplus: Fix compile with deprecated APIs disabled.

---

include/ipmitool/ipmi_channel.h
include/ipmitool/ipmi_intf.h
lib/ipmi_channel.c
lib/ipmi_main.c
src/plugins/ipmi_intf.c
src/plugins/lanplus/lanplus.c

Based on current crypto alogrithms, one could rank cipher suites along
these lines:
17 > 3 >> all the rest
17 and 3 are the only cipher suites that implement any sort of
confidentiality alogorithm that is secure. In addition, any hmac-md5 or
md5 integrity algorithm used in integrity is weak at best and dangerous
for authentication.
This could possibly be enabled in a simpler mechanism by simply checking
for 17 and then choosing it before falling back to 3, but the way this
is implemented, it makes it easy to change the list of acceptable
algorithms from two to three or more items.
Signed-off-by: Vernon Mauery <vernon.mauery@intel.com>

Auto selection of 'best' cipher suite available

---

include/ipmitool/ipmi_sdr.h
lib/helper.c
lib/ipmi_dcmi.c
lib/ipmi_fru.c
lib/ipmi_main.c
lib/ipmi_sdr.c
lib/ipmi_sdradd.c
lib/ipmi_sensor.c
src/plugins/ipmi_intf.c

I really don't like seeing so many compiler warnings when ipmitool builds. This is the first round of removing a few of them.

Cleanup compiler warnings

---

src/plugins/lanplus/lanplus.c

Correct segment violation in lanplus from dcmi truncated response.
This corrects Issue #72.
On occasion a dcmi power reading will return error C6, and a
truncated response payload. As the decrypted payload is shorter
than the expected length, lanplus_decrypt_aes_cbc_128() adjusts
the payload_size downward by one byte. In ipmi_lan_poll_single()
the calculation to determine if the payload size has increased
erroniously sets extra_data_length to -1, with a subsequent
segv when calling a memmove to shift response data.
The fix is to check for a positive value in the extra_data_length.

Correct lanplus segment violation for truncated response.

---

include/ipmitool/helper.h

free_n() will free the memory and clear the pointer, which will reduce
the probability a developer will forget to clear the pointer after
freeing.
Resolves: #79
Signed-off-by: Patrick Venture <venture@google.com>

helper: add free_n method to handle clearing pointers

---

lib/ipmi_hpmfwupg.c

hpm: Replace return()s with gotos to appropriate labels (with or without closing file).

Rewrite function to centralized exiting

---

include/ipmitool/ipmi_fru.h
lib/ipmi_fru.c

Fru cleanup.  Clean branch, cherry-picked the changes where possible, recreated where not.  Left out the static cleanup as well.  That can be done more universally later.

fru: cleanup redux

---

src/plugins/open/open.c

Apply whitespace fixes via clang-format-6.0 to src/plugins/open/open.c
to cleanup spaces and fixup line lengths, etc.
Signed-off-by: Patrick Venture <venture@google.com>

open: cleanup and bugfix

---

lib/ipmi_dcmi.c

Fix word typo `capabilties` which should be `capabilities`
```
$ ipmitool -I lanplus -H xx.xx.xx.xx -U root -P 0penBmc dcmi discover
Supported DCMI capabilities:
Mandatory platform capabilties
Optional platform capabilties
```
Signed-off-by: George Keishing <gkeishin@in.ibm.com>

Fix IPMI DCMI message typo

---

lib/ipmi_pef.c

fix for https://bugzilla.redhat.com/show_bug.cgi?id=1627527

Fix "ipmitool pef {status,info}" not printing final newline

---

.travis.yml
configure.ac
src/plugins/Makefile.am
src/plugins/dbus/Makefile.am
src/plugins/dbus/dbus.c
src/plugins/ipmi_intf.c

OpenBMC runs a D-Bus interface internally and has the option of
compiling ipmitool so it can run natively on the BMC. This adds the
new OpenBMC IPMI D-Bus interface to ipmitool so it can be used
with the OpenBMC project.
Signed-off-by: Vernon Mauery <vernon.mauery@linux.intel.com>

add OpenBMC D-Bus interface

---

configure.ac
src/plugins/Makefile.am
src/plugins/ipmi_intf.c

In some cases, the user may want to have a different default interface
without the need to always specify it on the command line. Add a
configure option that sets the default interface without the need to
patch the code.
Configure as: ./configure DEFAULT_INTF=name
where name is an interface name that might be enabled with
--enable-intf-<name>.
The configure will enforce that the selected default interface is
enabled.
Signed-off-by: Vernon Mauery <vernon.mauery@intel.com>

Add mechanism to configure to set the default interface

---

include/ipmitool/ipmi_sdr.h
lib/ipmi_sdr.c

The program would crash if the BMC returned an out of range (>90)
unit type for a full sensor record. This commit adds a range check
and also add support for IPMI 2.0 additional unit types 91 and 92
("fatal error" and "grams").
Resolves ipmitool/ipmitool#118

sdr: Fix segfault on invalid unit types

---

lib/create_pen_list

If a build environment doesn't have network access the fetch of the IANA PEN list will fail and the create_pen_list script will create invalid output causing the build to fail. This fixes the parsing.

create_pen_list: only print if values are set

---

configure.ac

Prior to 95038ba01b99153de870dde91406bdc1c7265217 the default interface
was 'open' for builds where it was available and 'lan' otherwise. Due to
a logic error in 95038ba01b99153de870dde91406bdc1c7265217, the default
interface was always getting set to lan unless it was specified by the
environment variable. This commit fixes the logic and sets the default
to open if it is available and lan otherwise.
Resolves ipmitool/ipmitool#128
Tested: ./configure # no options reports 'open' as default
./configure --enable-intf-open=no # reports lan as default
./configure --enable-intf-dbus DEFAULT_INTF=dbus
Signed-off-by: Vernon Mauery <vernon.mauery@intel.com>

Fix default interface to behave as it did before

---

include/ipmitool/helper.h
lib/helper.c

If a manufacturer's IANA PEN (aka manufacturer ID) was above
65535, it wasn't reported properly. Luckily there are no such
IDs so far, the biggest is 54077 as of 2019/06/18.
There is, however, an ID 0xFFFFFE used by fake_ipmistack
for debug purposes, and it was not reported correctly.
This commit expands the value argument to string searching functions
from 16-bit to 32-bit to allow for any possible IANA PEN.
Fixes: 73d6af57827fc85e78c700ca1dff00b3dbc63948

mc: Fix reporting of manufacturers > 64K

---

src/plugins/lanplus/lanplus.c

fix embedded bridged responses handling

---

doc/ipmitool.1.in
lib/ipmi_user.c

Some small changes to the tool documentation / man page to make it clearer how the password length argument is handled.

Improve clarity of the "set password" length argument

---

INSTALL

Add some documenation on packages to install on Ubuntu 16.04 before
building the software.
This will make it easier for people who are building ipmitool as they
won't need to figure out all the package dependencies on their own.

Docs: Add info on packages to install on Ubuntu 16.04 and Fedora 31

---

lib/ipmi_dcmi.c

This re-enables "nm policy add" functionality.

ipmi_dcmi: fix typo in nm_policy_options initialization.

---

lib/ipmi_hpmfwupg.c

Relying on sys/param.h's MAX() definition is not portable.

define non-portable MAX() if not defined in ipmi_hpmfwupg.c

---

lib/ipmi_sel.c

The current behavior:
- correct date format is not accepted by "sel time set".
- incorrect date format that looks correct is accepted, but time is not
set correctly.
- commands like
ipmitool sel time set "11/22/2013 trash"
are accepted.

ipmi_sel_set_time: fix strptime() return check

---

lib/ipmi_sdr.c

On one of our production systems (Supermicro X9DRD-7LN4F based), ipmitool sensor was occasionally crashing. This was due to it sometimes returning a junk SDR of the form:
```
SDR record ID   : 0x008a
SDR record id mismatch: 0x000a
SDR record type : 0x00
SDR record next : 0x0000
SDR record bytes: 100
```
or something similar. In this case, when we request the SDR data, we're getting back 0xca. However, ipmi_sdr_get_record() can underflow sdr_max_read_len to a negative value in this case. Harden the code for this.
Also, fix the addition of i to use the correct amount: it doesn't actually matter, since we'll check for i < len in the loop condition, but still.

harden ipmi_sdr_get_record() against bad records

---

configure.ac

Remove a bashims from configure to make build compatible
with systems without bash.
Resolves ipmitool/ipmitool#205

configure: Fix compatibility with non-bash systems

---

.github/workflows/ci.yml
INSTALL

doc, ci: Fix an error in package name for Windows

---

lib/ipmi_main.c
lib/ipmi_strings.c
lib/log.c

- Initialize the log at the start of ipmi_main() to allow for proper
logging at the start;
- Remove the unused log_level_get() function;
- Update log_level_set() to take verbosity instead of log level
(default verbosity is 0, which is LOG_NOTICE log level),
use the function to update log level as `-v` is encountered
in command line;
- Move IANA PEN list debugging to verbosity 6. The list is too long
to see it in each debug output of verbosity 5 that is used for
debugging lan/lanplus packets;
- For verbosity >= 2 (that is `-vv`) add the ipmitool version
information at the start.

Add version info to debug output

---

lib/ipmi_fru.c

Fix calculation of the buffer size for decoded 6-bit ASCII
strings. Previously the program could allocate too a short buffer
that caused buffer overflows and segmentation fault crashes on
certain FRU contents.

fru: Fix crashes on 6-bit ASCII strings

---

include/ipmitool/ipmi_hpmfwupg.h
lib/ipmi_hpmfwupg.c

- Drop a useless `extern` definition
- Remove static variable `errorCount` from header, move it to
the c file where it is actually used if needed
Related to ipmitool/ipmitool#220

hpmfwupg: Clean up / refactor

---

control/ipmitool.spec.in

When building an RPM, --with-kerneldir is passed to ./configure. This adds
the include path /lib/modules/<kversion>/build/include that may break the
build but is not present when building with "make" so useless.
For instance while building ipmi_sel.c with kernel 5.3.7-301.fc31.x86_64 :
/lib/modules/5.3.7-301.fc31.x86_64/build/include/linux/stddef.h:11:2: error:
expected identifier before numeric constant
11 |  false = 0,
|  ^~~~~
Signed-off-by: Gilles Buloz <gilles.buloz@kontron.com>

RPM support: fixed broken build due to use of headers from kernel

---

lib/ipmi_tsol.c

This patch has been added to fix "error: comparison between signed
and unsigned integer expressions [-Werror=sign-compare]"
Signed-off-by: Shitalkumar Gandhi <shitalkumar.gandhi@seagate.com>

Fixed compiler warning.

---

doc/ipmitool.1.in

Modify the documentation to reflect commit 7772254b ("lanplus: Auto-select
'best' cipher suite available") which changed the default cipher suite for
lanplus from 3 to 17

doc: update lanplus doc to reflect default cipher suite change

---

lib/ipmi_lanp.c

Both 'Set/Get LAN Configuration Parameter' commands may return
command-specific codes that weren't properly parsed and were
reported as 'Unknown' before. This is fixed now.

lan: Add processing of get/set specific CCs

---

include/ipmitool/ipmi_mc.h

The IPM_DEV_FWREV1_MAJOR_MASK was incorrectly defined as 0x3F.
The spec indicates that the major firmware revision has 0~6 valid bits,
so the mask shall be 0x7F.
Tested: Verify a BMC that has a major version that is large than 0x3F,
and ipmitool shows the correct major version.
Signed-off-by: Lei YU <yulei.sh@bytedance.com>

ipmi_mc: Fix the IPM_DEV_FWREV1_MAJOR_MASK

---

.github/workflows/ci.yml

Update the CI configuraion to reflect the latest changes on GitHub.
See:
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
https://github.blog/changelog/2021-09-29-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-big-sur-11/

Feature/update GitHub actions

---

src/plugins/open/open.c

This was caught via a sanitized build where the recv was used with stack data in some cases.

zero initialize the recv structure on the stack

---

lib/ipmi_sel.c

There is no need to reserve SEL when doing "sel list" and "sel get"
since we don't do partial get in both commands, and we didn't even use
the reservation ID returned by "Reserve SEL".
Signed-off-by: Bing-Hua Wang <binghuawang@ami.com>

sel: Remove redundant "Reserve SEL"

---

include/ipmitool/ipmi_strings.h
lib/ipmi_chassis.c
lib/ipmi_strings.c

Add 'soft reset' and 'power-up by RTC wakeup' causes
from IPMI 2.0 spec.
Resolves ipmitool/ipmitool#329

chassis restart_cause: Add new causes

---

lib/ipmi_sel.c

The choice of `>` or `<` when printing the threshold inequality currently only depends on whether it is an upper or lower threshold. This is correct when the event is asserted, but when the event is deasserted the inequality is reversed and therefore the current code can give confusing results, e.g.:
```
3cb | 07/17/2022 | 06:15:39 | Temperature ps1_inlet_temp | Upper Non-critical going high | Deasserted | Reading 43.94 > Threshold 44.88 degrees C
```
(Note `Reading 43.94 > Threshold 44.88`)
This PR fixes this by inverting the sign when the event is deasserted:
```
3cb | 17/07/22 | 07:15:39 BST | Temperature ps1_inlet_temp | Upper Non-critical going high | Deasserted | Reading 43.94 < Threshold 44.88 degrees C
```

SEL printing: Invert the threshold inequality when an event is deasserted

---

include/ipmitool/helper.h

Building ipmitool with UBSAN and I got:
```
...
xxx/ipmitool/include/ipmitool/helper.h:191:14: runtime error: left shift of 160
by 24 places cannot be represented in type 'int'
#0 0x55bddaa56f11 in ipmi32toh
xxx/ipmitool/include/ipmitool/helper.h:191:14
```
Tested: with this, I tested ipmitool again and the issue disappeared.
Resolved: ipmitool/ipmitool#352
Signed-off-by: Tom Tung <shes050117@gmail.com>

Cast type before the left shift

---

include/ipmitool/ipmi_fru.h
include/ipmitool/ipmi_mc.h
lib/ipmi_fru.c
lib/ipmi_mc.c

* Add a decoder for System Management records in the Multirecord area
* Refactor GUID/UUID decoding: Use the same code for `mc guid` and
for `fru print` to decode the GUID and System Unique ID in
System Management records in the Multirecord Area.
* Fix some type errors in calls to printf/sprintf in GUID decoder

fru: Add decoder for multirec system mgmt records
